config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home', to: "home#index"
  get 'portfolio', to: "albums#index"
  get 'dashboard', to: "home#edit", :as => "dashboard"
  get 'sign_up', to: "users#new", :as => "sign_up"
  get 'login', to: "sessions#new", :as => "login"
  get 'logout', to: "sessions#destroy", :as => "logout"

  resources :home
  resources :users, only: [:new, :create]
  resources :sessions
  resources :posts
  resources :albums
  resources :pictures

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :pictures
  has_one :primary_photo
  has_one :secondary_photo
  validates_presence_of :title
  accepts_nested_attributes_for :pictures

  def first_pictures
    pictures.first(4)
  end

  def to_param
    "#{id}-#{title}"
  end

end

app/models/home.rb
class Home < ActiveRecord::Base
  has_many :posts



end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :album
  mount_uploader :photo, PhotoUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :body, :title
  mount_uploader :image, ImageUploader
  mount_uploader :image2, Image2Uploader
  mount_uploader :image3, Image3Uploader



end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  has_many :albums
  has_many :pictures

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < InheritedResources::Base
  actions :index, :new, :show
  before_filter :require_user, except: [:index, :show]

  def new
    @album = Album.new
  end

  def edit
    @album = Album.find(1)
    @picture = @album.pictures.find_by(:id)
  end

  def create
    @album = Album.new(album_params)
    @album.save!
    if @album.save
      flash[:success] = "You created a new Gallery Category!"
      redirect_to albums_path
    else
      flash[:error] = "There was a problem with your title"
      render :new
    end
  end

  def destroy
    @album = Album.find(album_params)
    @album.destroy
  end

  private
  def album_params
    params.require(:album).permit(:title, :pictures)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_user
    redirect_to login_path unless current_user
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_user, only: [:edit]

  def index
    @post = Post.order("created_at").last
    @nextpost = Post.order("created_at")[-2]
  end

  def show
  end

  def edit
  end
end

app/controllers/pictures_controller.rb
class PicturesController < InheritedResources::Base
  actions :show
  before_filter :require_user, except: [:index, :show]


  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to albums_path
    else
      format.html { render action: "new" }
    end
  end


  def index
    @pictures = Picture.all
    @album = Album.all

    respond_to do |format|
      format.html
      format.json { render json: @pictures }
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to albums_path
  end

  private

  def picture_params
    params.require(:picture).permit(:photo, :caption, :album_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # actions :new, :create, :edit, :update, :show, :index
  before_action :require_user, except: [:show, :index]


  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save!
    if @post.save
      flash[:success] = "Your Pick was posted!"
      redirect_to posts_path
    else
      flash[:error] = "There was a problem with your post."
      render :new
    end
  end

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Your Post was updated!"
      redirect_to post_path(@post)
    else
      flash[:error] = "There was a problem with your post."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
    flash[:success] = "Your Post was deleted!"
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :image2, :image3)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to dashboard_path, :notice => "Logged In!"
    else
      flash.now.alert = "Wrong email or password. Please Try again"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed Up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_salt, :password_hash)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.haml
= form_for @album do |f|
  - if @album.errors.any?
    #error_explanation
      %h2= "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
      %ul
        - @album.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/albums/edit.html.haml
%section#primaryphotos
  .form-horizontal
    = bootstrap_form_for :album do |primary_form|
      = primary_form.fields_for :primary_photo do |primary_fields|
        %h1 Edit Pictures on Home Page
        %br
        %h3 Top picture
        %p
          = f.select :primary_photo, options_for_select(@album.pictures, picture.id)
          %br/
          %br/

= link_to 'Back', pictures_path

app/views/albums/index.html.haml
.container#content
  .row.col-lg-10.col-lg-offset-1#portfolio
    .row#pagehead
      =link_to root_path, class: "btn btn-default" do
        %i.glyphicon.glyphicon-arrow-left.pull-left
      %br
    - @albums.each do |album|
      %hr/
      %h3.template-title= link_to album.title, album_path(album)
      %hr/
      %br
      .row#thumbs
        - album.pictures.sort_by{|t| - t.created_at.to_i}.first(4).each do |picture|
          .col-md-3.thumb
            = link_to picture do
              %img.thumbnail.img-responsive(src="#{picture.photo}")
              %br

app/views/albums/new.html.haml
%h1 New album

= render 'form'

= link_to 'Back', albums_path

app/views/albums/show.html.haml
.container#content
  .row.col-lg-10.col-lg-offset-1#portfolio
    .row#pagehead
      =link_to root_path, class: "btn btn-default" do
        %i.glyphicon.glyphicon-arrow-left.pull-left
      %br
    %hr/
    %h3.template-title= @album.title
    %hr/
    %br
    .row#thumbs
      - @album.pictures.each do |picture|
        .col-md-3
          = link_to picture do
            %img.thumbnail.img-responsive(src="#{picture.photo}")
            %br

app/views/home/edit.html.haml
.container#content
  .row#dashboard
    %h1 Hi Orlene!
    %br/
    %br/
    %h3= link_to "New Post in My Picks", new_post_path
    %br/
    %br/
    %h3= link_to "Edit a post in My Picks", posts_path
    %br/
    %br/
    %h3= link_to "Add Photos to the Gallery", new_picture_path
    %br/
    %br/
    %h3= link_to "Go to My Email", "http://webmail.laughingwithflowers.com/", target: '_blank'
    %br
    %h4.pull-left= link_to "Log Out", logout_path

app/views/home/index.html.haml
.container#content
  .col-lg-3#blog-column
    %hr/
    %h3= link_to 'My Picks', posts_path
    %hr/
    %h4= link_to @post.title, post_path(@post)
    %br
    .img-responsive.center-block#minipostimage= image_tag @post.image_url.to_s
    %br
    %p= @post.body
    %br
    %hr
    %br
    %h4= link_to @nextpost.title, post_path(@nextpost)
    %br
    .img-responsive.center-block#minipostimage= image_tag @nextpost.image_url.to_s
    %br
    %p= @nextpost.body
    %br
    %hr/
    .section#contact
      %h3 Contact
      %hr/
      %br
      %a.small(href="mailto:orlene@laughingwithflowers.com") orlene@laughingwithflowers.com
      %br
      %br
      %h4 503-241-0336
      %br
      %h4 Portland, Oregon
      %br
      %br
      %img{src: "#{image_path('portland.png')}", class: "img-responsive"}
  .col-lg-5#wedding-column
    %br
    %hr/
    %h3= link_to 'Weddings', album_path(1)
    %hr/
    %br/
    %img{src: "#{image_path('caketopper.jpg')}", class: "img-responsive"}
    %img{src: "#{image_path('headbandthumb.jpg')}", class: "img-responsive"}
    %br
    .row.col-lg-10.col-lg-offset-1#about
      %hr/
      %h3 About
      %hr/
      %br
      %p As an Oregon native, I specialize in local, in-season flowers and greenery. My unique style gives a soft edge and flair to my arrangements. My experience includes 16 years of being in the floral industry from cultivating a flower farm, to numerous years working with nursery product, while designing in high end floral shops from east to west coast.  While working with flowers is my passion, I also find time to work in a greenhouse propagating succulents.
      %br
      %br
  .col-lg-3#terr-column
    %hr/
    %h3= link_to 'Terrariums', album_path(2)
    %hr/
    %img{src: "#{image_path('terr3thumb.jpg')}", class: "img-responsive"}
    %br/
    %img{src: "#{image_path('terr1thumb.jpg')}", class: "img-responsive"}
    %br/
    %img{src: "#{image_path('terr2thumb.jpg')}", class: "img-responsive"}
    %br/
    %img{src: "#{image_path('terr4thumb.jpg')}", class: "img-responsive"}
    %br/
    %img{src: "#{image_path('terr6thumb.jpg')}", class: "img-responsive"}
    %br/
    %img{src: "#{image_path('terr5thumb.jpg')}", class: "img-responsive"}
    %br/
    %br/
    .well#delivery
      %h5 Delivery available upon request in the Portland metro area.

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.chose(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Laughing With Flowers</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link href="http://fonts.googleapis.com/css?family=Dawning+of+a+New+Day" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="container-fluid col-lg-12" id="background">
      <div class="container container-centered col-lg-10 col-lg-offset-2" id="main">
        <div class="row header">
          <%= render 'layouts/messages' %>
          <!-- <div class="brand"><h1>Laughing With Flowers</h1></div> -->
          <nav class="navbar navbar-default navbar-fixed" role="navigation">
            <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="menu-items">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><h1>Laughing With Flowers</h1></a>
              </div>
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="menu-items">
                <ul class="nav navbar-nav pull-right">
                  <li><a href="/"><h4>Home</h4></a></li>
                  <li><a href="/posts"><h4>Blog</h4></a></li>
                  <li><a href="/portfolio"><h4>Portfolio</h4></a></li>
                  <!-- <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      <h4>Portfolio</h4><span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="/portfolio">Portfolio</a></li>
                      <li class="divider"></li>
                      <li><a href="/albums/1-Weddings">Weddings</a></li>
                      <li><a href="/albums/2-Terrariums">Terrariums</a></li>
                      <li><a href="/albums/3-Events">Events</a></li>
                    </ul>
                  </li> -->
                  <li><a href="/#contact"><h4>Contact</h4></a></li>
                  <% if current_user %>
                    <li><a href="/dashboard"><h4>Dashboard</h4></a></li>
                  <% end %>
                </ul>
              </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
          </nav>
        </div>
        <%= yield %>
      </div>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="javascripts/jquery.singlePageNav.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pictures/_form.html.haml
%section#newphotos
  .form-horizontal
    = bootstrap_form_for(@picture, :html => {:multipart => true}) do |f|
      %p
      - if @picture.errors.any?
        #error_explanation
          %h2= "#{pluralize(@picture.errors.count, "error")} prohibited this picture from being saved:"
          %ul
            - @picture.errors.full_messages.each do |msg|
              %li= msg
      %p
        = f.file_field :photo
      %p
        = f.select :album_id, options_for_select(Album.all.map {|album| [album.title, album.id]})
        %br/
        %br/
      = f.submit 'Upload Picture', class: 'btn btn-primary'

app/views/pictures/index.html.haml
%h1 Portfolio
- @album.each do |album|
  %hr/
  %h3.template-title= album.title
  %hr/
  %br
  .row#thumbs
    - @pictures.each do |picture|
      .col-md-3
        .well
          =link_to image_tag(picture.photo.url, picture_path(@picture))
= link_to 'New Picture', new_picture_path

app/views/pictures/new.html.haml
%h1 New picture

= render 'form'

= link_to 'Back', pictures_path

app/views/pictures/show.html.haml
.container#contentimage
  .col-sm-12#portfolioshow
    =link_to albums_path, class: "btn btn-default" do
      %i.glyphicon.glyphicon-arrow-left.pull-left
    %br
    %br
    %img.img-responsive.center-block(src="#{@picture.photo}")
  %br
  %br
  %br
  .actions
    - if current_user
      %h4= link_to "(Remove Picture)", picture_path(@picture), :confirm => 'Are you sure you want to delete this photo?', :method => :delete

app/views/posts/_form.html.haml
%section#mypicks_form
  .form-horizontal
    = bootstrap_form_for(@post, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10", :html => {:multipart => true}) do |f|
      %p
        = f.text_field :title
      %p
        = f.text_area :body, rows: 6
      %p
        = f.file_field :image
        .row-centered (This will be the top picture in the post)
        %br/
      %p
        = f.file_field :image2
        .row-centered (This will be the middle picture in the post)
        %br/
      %p
        = f.file_field :image3
        .row-centered (This will be the bottom picture in the post)
        %br/
      .col-sm-6.col-md-offset-3
        = f.submit(@post.new_record? ? "Post Your Pick" : "Save", class: 'btn btn-success')
      %br/
      %br

app/views/posts/_post.html.haml
.well.col-sm-10.col-sm-offset-1#post
  %h4#posttitle= link_to post.title, post_path(post)
  %br
  %h4.small= post.created_at.to_date.to_formatted_s(:long_ordinal)
  %br
  .col-sm-6.col-sm-offset-3#postbody
    %p= post.body
    %br/
  .row
    .img.img-responsive.center-block#postimage= image_tag post.image_url.to_s
    %br/
  .row
    .img.img-responsive.center-block#postimage= image_tag post.image2_url.to_s
    %br/
  .row
    .img.img-responsive.center-block#postimage= image_tag post.image3_url.to_s
    %br/
  - if current_user
    %h4= link_to 'Edit', edit_post_path(post)
    %h4= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }
    %br
  %br
  %br
  %br

app/views/posts/edit.html.haml
.container#content
  .row#form
    %h3 Edit this post
    %br
    = render 'form'
    %br
  #bottom-links
    %h4= link_to 'View Post', @post
    %h4= link_to 'All Posts', posts_path
    %h4= link_to 'Write a new Post', new_post_path

app/views/posts/index.html.haml
.container#content
  .col-sm-12#postsindex
    %h2 Recent posts
    =link_to root_path, class: "btn btn-default" do
      %i.glyphicon.glyphicon-arrow-left.pull-left
    %br
    - @posts.each do |post|
      = render 'post', post: post
    %br/

app/views/posts/new.html.haml
%h3 New My Pick
= render 'posts/form' 

app/views/posts/show.html.haml
.container#content
  .col-sm-12#showpost
    =link_to posts_path, class: "btn btn-default" do
      %i.glyphicon.glyphicon-arrow-left.pull-left
    %br
    = render 'post', post: @post

app/views/users/new.html.haml
%h3 Create a Login

= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Try again
      %ul
        - for message in @user.errors.full_messages
          %li= message
  %p
    = f.label :email
    %br/
    = f.text_field :email
  %p
    = f.label :password
    %br/
    = f.password_field :password
  %p
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  %p.button= f.submit